# Generated by Django 6.0.1 on 2026-01-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuperHero',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('alignment', models.CharField(db_index=True, max_length=20)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('intelligence', models.IntegerField(default=0)),
                ('strength', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=0)),
                ('durability', models.IntegerField(default=0)),
                ('power', models.IntegerField(default=0)),
                ('combat', models.IntegerField(default=0)),
                ('biography', models.JSONField()),
                ('appearance', models.JSONField()),
                ('work', models.JSONField()),
                ('connections', models.JSONField()),
            ],
        ),
    ]
