# Generated by Django 6.0.1 on 2026-01-24 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_hero', '0002_favoritehero'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('team_type', models.CharField(choices=[('balanced', 'Balanced'), ('power', 'Power Based'), ('random', 'Random'), ('favorites', 'Favorites Based')], max_length=20)),
                ('power_category', models.CharField(blank=True, max_length=20, null=True)),
                ('team_strength', models.CharField(blank=True, choices=[('strong', 'Strong'), ('weak', 'Weak'), ('average', 'Average')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_hero.superhero')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='super_hero.team')),
            ],
            options={
                'unique_together': {('team', 'hero')},
            },
        ),
    ]
